support installing archived binaries

diff --git a/bin/install_bin b/bin/install_bin
--- a/bin/install_bin
+++ b/bin/install_bin
@@ -4,11 +4,35 @@ if [[ "$1" == "" ]]; then
     echo "Check if a bin exists before attempting to install, exits with 1 if any packages get installed"
     exit 0
 fi
+
+BIN=/usr/bin
+
+if [[ "$(uname)" == "Darwin" ]]; then
+    BIN=/usr/local/bin
+fi
+
 for pkg in "$@"; do
     name=$( basename $pkg)
-    name=${name%.*}
-    if [[ ! -e /usr/bin/$name ]]; then
-        curl -k $pkg > /usr/bin/$name
-        chmod +x /usr/bin/$name
+    base=${name%.*} # remove extension
+    bin=$(echo $base | cut -d_ -f1) # strip off os_platform like params
+    if [[  "$force" != "true" && -e $BIN/$bin ]]; then
+        exit 0
     fi
+
+    tmp=$(mktemp -d)
+    wget -O $tmp/$name --no-check-certificate $pkg
+    if [[ "$name" != "$base" ]]; then
+        cd $tmp
+        extract $name
+    fi
+    if [[ -e $tmp/$base ]]; then
+        mv $tmp/$base $BIN/$bin
+    elif [[ -e $tmp/bin ]]; then
+        mv $tmp/$bin $BIN/$bin
+    else
+        echo "Unable to detect bin name in $(ls)"
+        exit 1
+    fi
+    chmod +x $BIN/$bin
+
 done
